### ISSUE TITLE
 'cabal install nettle-openflow' fails at [ 7 of 24] Compiling Nettle.IPv4.IPPacket

### ISSUE THREAD

**Issue by Phi-Ho** [AndreasVoellmy/openflow#3]
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ ghc-pkg list | grep network
    network-2.4.1.2

$ cabal install nettle-openflow
Resolving dependencies...
Configuring nettle-openflow-0.2.0...
Building nettle-openflow-0.2.0...
Preprocessing library nettle-openflow-0.2.0...
[ 1 of 24] Compiling Nettle.Topology.ExtendedDouble ( src/Nettle/Topology/ExtendedDouble.hs, dist/build/Nettle/Topology/ExtendedDouble.o )
[ 2 of 24] Compiling Nettle.Topology.LabelledGraph ( src/Nettle/Topology/LabelledGraph.hs, dist/build/Nettle/Topology/LabelledGraph.o )
[ 3 of 24] Compiling Nettle.Topology.FloydWarshall ( src/Nettle/Topology/FloydWarshall.hs, dist/build/Nettle/Topology/FloydWarshall.o )
[ 4 of 24] Compiling Nettle.OpenFlow.Error ( src/Nettle/OpenFlow/Error.hs, dist/build/Nettle/OpenFlow/Error.o )
[ 5 of 24] Compiling Nettle.OpenFlow.StrictPut ( src/Nettle/OpenFlow/StrictPut.hs, dist/build/Nettle/OpenFlow/StrictPut.o )
[ 6 of 24] Compiling Nettle.IPv4.IPAddress ( src/Nettle/IPv4/IPAddress.hs, dist/build/Nettle/IPv4/IPAddress.o )
[ 7 of 24] Compiling Nettle.IPv4.IPPacket ( src/Nettle/IPv4/IPPacket.hs, dist/build/Nettle/IPv4/IPPacket.o )

src/Nettle/IPv4/IPPacket.hs:71:26:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:71:37:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:71:41:
    Not in scope: type constructor or class `HNil'
    A data constructor of that name is in scope; did you mean -XDataKinds?
    Perhaps you meant HNil' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:116:45:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:116:49:
    Not in scope: type constructor or class `HNil'
    A data constructor of that name is in scope; did you mean -XDataKinds?
    Perhaps you meant HNil' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:117:38:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:117:49: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:121:45:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:121:62:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:121:66:
    Not in scope: type constructor or class `HNil'
    A data constructor of that name is in scope; did you mean -XDataKinds?
    Perhaps you meant HNil' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:122:42:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:122:53:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:122:64: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:126:79:
    Not in scope: type constructor or class `:*:'

src/Nettle/IPv4/IPPacket.hs:127:28:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:185:110:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:185:121:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:185:144: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:189:55:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:189:66:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:189:94: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:190:111:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:190:122:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:190:147: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:193:63:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:193:74:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:193:122: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:202:84:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:202:95:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:202:118: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:205:55:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:205:66:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:205:94: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:206:85:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:206:96:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:206:121: Not in scope: `hNil'

src/Nettle/IPv4/IPPacket.hs:208:61:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:208:72:
    Not in scope: `hCons'
    Perhaps you meant `hCond' (imported from Data.HList)

src/Nettle/IPv4/IPPacket.hs:208:120: Not in scope: `hNil'
Failed to install nettle-openflow-0.2.0
cabal: Error: some packages failed to install:
nettle-openflow-0.2.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by AndreasVoellmy** [comment]
The IPPacket representations have been completely changed, so I believe this is no longer an issue.
