### ISSUE TITLE
pushing the upper bound on aeson dependency

### ISSUE THREAD

**Issue by ryzhyk** [AndreasVoellmy/openflow#6]
Thanks for the great library, @AndreasVoellmy ! It's great to be able to work with OpenFlow natively from Haskell.

The openflow.cabal file requires aeson  <= 0.9.0.1. This prevents me from using the library in a project that  uses a more recent version of aeson. Removing this constraint, I discovered that the library happily compiles and (based on very limited testing) works with aeson 1.2.1.0. I was wondering if there's any chance the bound could be pushed to 1.2 or removed in the github repo, as well as on hackage?

Thanks,
Leonid

**Comment by AndreasVoellmy** [comment]
Hi Leonid,

Yes, that seems fine to me. I'll push an update soon.

**Comment by AndreasVoellmy** [comment]
Updated to 0.3.1 with upper bounds on aeson and blimp removed. I also released to package.
